#!/bin/sh
# Author: Piotr Lewandowski <piotr.lewandowski@cert.pl>
#
# (Re)start VirtualBox machine and make sure that VBoxSVC is running.
set -e

name="${2:?name}"
cmd="/usr/lib/virtualbox/VBoxHeadless -s $name"

singleton()
{
	pattern="$1"
	shift
	# Zombie processes should be not taken into account.
	pgrep -f "$pattern" | xargs --no-run-if-empty ps --no-headers --format s,pid -p | grep -v ^Z >/dev/null || $@
}

pkill -SIGTERM -f -x "$cmd" || true
singleton 'VBoxSVC' '/usr/lib/virtualbox/VBoxSVC --automate'

# Unfortunately, VBoxHeadless won't start if run just after if previous
# instance was killed. Thus, we have to try till we succeed.
# If you are curious why - replace /dev/null with a regular file.

while ! pgrep -f -x "$cmd" >/dev/null; do
	nohup >/dev/null 2>&1 $cmd &
	sleep 0.1
done
